name: "Deploy"

on:
  workflow_dispatch:

env:
  targetEnv: Dev

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    # Checkout code
    - uses: actions/checkout@m2.5.0

      # Log into Azure
    - uses: azure/loginv@v1.4.6
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1.0.8
      with:
        scope: resourcegroup
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: "WTH-GitHub-RG"
        template: "ARM-Templates/container-webapp-template.json"
        parameters: webAppName=WTHApp-${{ env.targetEnv }}
        deploymentMode: Incremental
